# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/resources/ui/window.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(943, 530)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.task_list_widget = QtWidgets.QListWidget(self.centralwidget)
        self.task_list_widget.setObjectName("task_list_widget")
        self.gridLayout.addWidget(self.task_list_widget, 3, 0, 1, 1)
        self.delete_all_btn = QtWidgets.QPushButton(self.centralwidget)
        self.delete_all_btn.setStyleSheet("background-color: rgb(136, 15, 17)")
        self.delete_all_btn.setObjectName("delete_all_btn")
        self.gridLayout.addWidget(self.delete_all_btn, 10, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.complete_btn = QtWidgets.QPushButton(self.centralwidget)
        self.complete_btn.setStyleSheet("background-color: rgb(10, 161, 255)")
        self.complete_btn.setObjectName("complete_btn")
        self.horizontalLayout_3.addWidget(self.complete_btn)
        self.uncomplete_btn = QtWidgets.QPushButton(self.centralwidget)
        self.uncomplete_btn.setStyleSheet("background-color: rgb(157, 157, 157)")
        self.uncomplete_btn.setObjectName("uncomplete_btn")
        self.horizontalLayout_3.addWidget(self.uncomplete_btn)
        self.gridLayout.addLayout(self.horizontalLayout_3, 7, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.new_task_btn = QtWidgets.QPushButton(self.centralwidget)
        self.new_task_btn.setStyleSheet("background-color: rgb(50, 181, 72)")
        self.new_task_btn.setObjectName("new_task_btn")
        self.horizontalLayout_4.addWidget(self.new_task_btn)
        self.delete_btn = QtWidgets.QPushButton(self.centralwidget)
        self.delete_btn.setStyleSheet("background-color:rgb(202, 27, 11)")
        self.delete_btn.setObjectName("delete_btn")
        self.horizontalLayout_4.addWidget(self.delete_btn)
        self.gridLayout.addLayout(self.horizontalLayout_4, 5, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.edit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.edit_btn.setStyleSheet("background-color: rgb(187, 202, 18)")
        self.edit_btn.setObjectName("edit_btn")
        self.horizontalLayout_2.addWidget(self.edit_btn)
        self.save_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_btn.setStyleSheet("background-color: rgb(99, 148, 255)")
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout_2.addWidget(self.save_btn)
        self.gridLayout.addLayout(self.horizontalLayout_2, 9, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 4, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.delete_all_btn.setText(_translate("MainWindow", "Delete All"))
        self.complete_btn.setText(_translate("MainWindow", "Mark as completed"))
        self.uncomplete_btn.setText(_translate("MainWindow", "Mark as uncompleted"))
        self.new_task_btn.setText(_translate("MainWindow", "New"))
        self.delete_btn.setText(_translate("MainWindow", "Delete"))
        self.edit_btn.setText(_translate("MainWindow", "Edit"))
        self.save_btn.setText(_translate("MainWindow", "Save"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Task "))
